### ISSUE TITLE
Booting GentooX ISO on Linux Host results in "end Kernel Panic not syncing: Attempt to kill init!"

### ISSUE THREAD

**Issue by zdavatz** [fatalhalt/gentoox#4]
My host machine is Funtoo. Other OS's in VirtualBox work fine.
VirtualBox Version:
![latest-screenshot](https://user-images.githubusercontent.com/4953/98933106-822a0c00-24e0-11eb-8518-1eb5e6bf4aef.png)
Console output when starting up with `gentoo-nofb`
![redit](https://user-images.githubusercontent.com/4953/98933164-8eae6480-24e0-11eb-937a-eb473a9bf7b2.png)

**Comment by zdavatz** [comment]
[Logs.zip](https://github.com/fatalhalt/gentoox/files/5530193/Logs.zip)

**Comment by ucodelukas** [comment]
I am assuming that the custom kernel is just not compatible with VBox 

It was compiled with flags for real intel sandybridge CPUs to get performance out of it.

Maybe the VirtualBox cpu is just too old

**Comment by ucodelukas** [comment]
If I haven't misread the logs, this is the CPU it tries to run it on.

https://en.wikichip.org/wiki/intel/microarchitectures/p6

```
00:00:01.097192 Hst:                00000000 00000000 00000002 00000007
00:00:01.097193                                Name: GenuineIntel
00:00:01.097194                            Supports: 0x00000000-0x0000000b
00:00:01.097195                              Family:  6 	Extended: 0 	Effective: 6
00:00:01.097196                               Model: 10 	Extended: 1 	Effective: 26
00:00:01.097197                            Stepping: 5
00:00:01.097198                                Type: 0 (primary)
00:00:01.097199                             APIC ID: 0x00
00:00:01.097200                        Logical CPUs: 4
00:00:01.097200                        CLFLUSH Size: 8
00:00:01.097201                            Brand ID: 0x00
```

Can you confirm? Or try with the host CPU in Qemu

**Comment by zdavatz** [comment]
these are my CPUs, `cat /proc/cpuinfo` [cpuinfo.txt](https://github.com/fatalhalt/gentoox/files/5629288/cpuinfo.txt)

**Comment by ucodelukas** [comment]
yeah thats not the cpuid from VBox,

see upper post

**Comment by zdavatz** [comment]
I got it working, so you can close the issue now.

**Comment by ucodelukas** [comment]
can you close it yourself? i am just some rando
