### ISSUE TITLE
How to get rid of the theme reminder on boot?

### ISSUE THREAD

**Issue by ghost** [fatalhalt/gentoox#8]
I do not want to install the theme, I love how kde looks as is. It is something minor but I just want it gone as I don't like it taking up most of my screen every time i log in.

**Comment by fatalhalt** [comment]
Remove the ''~/postinstall.sh &' line from ~/.xinitrc located in your homedir.

If you have a wayland capable setup you could also start KDE with ./startkde-wayland.sh instead of startx.

**Comment by ghost** [comment]
Thank you.
